# Site settings

author: Deokhun Kim
email: deokhun0312@gmail.com
twitter_username:
github_username:  DeokhunKim
googleplus_username: 

head-title: 기록하면 후회하지 않는다
title: 기록하면 후회하지 않는다 - Do once archived, then no regrets

baseurl: ""    # the subpath of your site, "/blog"
url: "http://localhost:4000/"

# footer 
description: "I know that what I'm doing looks stupid, but I'm a big boy and really want to do this."

favo: ""
descrpt: ""


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "light-blue
head-theme-color: "#03a9f4"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "light-blue"
footer-button-color: "light-blue lighten-1"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

